apiVersion: v1
kind: ConfigMap
metadata:
    name: fintech-config
    namespace: {{ .Values.namespace }}
data:
    DB_HOST: "{{ .Values.yugabyteDB.name }}"
    DB_PORT: "5433"
    DB_NAME: "fintech"
    USER_SERVICE_URL: "http://{{ .Values.userService.name }}:{{ .Values.userService.service.port }}"

