apiVersion: v1
kind: Secret
metadata:
    name: db-credentials
    namespace: {{ .Values.namespace }}
type: Opaque
data:
  # base64 encoded "yugabyte"
  DB_USER: eXVnYWJ5dGU=
  DB_PASSWORD: eXVnYWJ5dGU=

# Additional templates would follow the same pattern for all services,
# matching the Kubernetes YAML manifests but templated with Helm