replicaCount: 1

image:
  repository: ${DOCKER_REGISTRY}/product-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

environment:
  - name: DB_HOST
    value: "yugabytedb"
  - name: DB_PORT
    value: "5433"
  - name: DB_USER
    value: "yugabyte"
  - name: DB_PASSWORD
    value: "yugabyte"
  - name: DB_NAME
    value: "yugabyte"