apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: fintech-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
      - name: apisix
        image: apache/apisix:latest
        ports:
        - containerPort: 9080
          name: http
        - containerPort: 9443
          name: https
        env:
        - name: APISIX_STAND_ALONE
          value: "true"
        volumeMounts:
        - name: apisix-config
          mountPath: /usr/local/apisix/conf/config.yaml
          subPath: config.yaml
      volumes:
      - name: apisix-config
        configMap:
          name: apisix-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
  namespace: fintech-app
data:
  config.yaml: |
    apisix:
      node_listen: 9080
      enable_admin: true
      enable_dev_mode: true
      allow_admin:
        - 0.0.0.0/0
---
apiVersion: v1
kind: Service
metadata:
  name: apisix
  namespace: fintech-app
spec:
  selector:
    app: apisix
  ports:
  - name: http
    port: 80
    targetPort: 9080
  - name: https
    port: 443
    targetPort: 9443
  type: LoadBalancer