apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: transaction-service-scaler
  namespace: fintech-app
spec:
  scaleTargetRef:
    name: transaction-service
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.monitoring.svc.cluster.local:9090
      metricName: http_requests_total
      threshold: "10"
      query: sum(rate(http_requests_total{app="transaction-service"}[2m]))
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: user-service-scaler
  namespace: fintech-app
spec:
  scaleTargetRef:
    name: user-service
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.monitoring.svc.cluster.local:9090
      metricName: http_requests_total
      threshold: "10"
      query: sum(rate(http_requests_total{app="user-service"}[2m]))